name: Build And Test

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.platform}}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v4
      id: go
      with:
        go-version: ${{matrix.go-version}}

    - name: Install Go Task Tool
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{secrets.GITHUB_TOKEN}}

    - name: Lint
      run: task lint

    - name: Test
      run: task test

    - name: Build
      run: task build
